#!/bin/bash

# Start Openbox
openbox &

# Launch Chrome maximized with performance flags
google-chrome-stable \
  --start-maximized \
  --no-sandbox \
  --disable-setuid-sandbox \
  --enable-features=HardwareAcceleration,VaapiVideoDecoder \
  --disable-gpu-driver-bug-workarounds \
  --ignore-gpu-blocklist \
  --enable-gpu-rasterization \
  --enable-zero-copy \
  --use-gl=desktop \
  --disable-features=Translate \
  --password-store=basic \
  https://www.google.com &

wait